FROM python:3.12-slim

WORKDIR /app

# Copy requirements directly from /backend
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy all source files from /backend into /app
COPY . .

CMD ["python", "main.py"]